Update the DVC: Get Started / Plots Dashboard
iterative/vscode-dvc pull request #2573
Opened 2022-10-12 14:59 UTC by maxagin

Select (click the circle beside the experiment name) one or more up to 7 experiments in the table view to visualize in the Plots Dashboard. screenshot
Use DVC: Show Plots from the command palette to open it or open it using the table's row context menu.

2022-10-12 22:21 UTC, shcheklein commented
Thanks @maxagin . The image should be also part of this PR please.

Also, please see in the file and wrap text at 80 symbols.

2022-10-13 18:37 UTC, maxagin commented
Sorry forgot to wrap the text. Will create an update

2022-10-13 21:24 UTC, shcheklein commented on extension/resources/walkthrough/plots.md
> +Select (click the circle beside the 🧪 experiment name) up to 7 experiments in
Let's please remove the emoji (we don't use them in the walkthrough this way).

2022-10-13 21:41 UTC, shcheklein requested changes
- We need to wait for the https://github.com/iterative/vscode-dvc/pull/2553 to land
- Please use https://tinypng.com/ to make sure that image is optimized

2022-10-20 00:50 UTC, shcheklein commented
The problem with this approach is that people don't see now the plots dashboard itself when they open the page (they would need to scroll). Should we change the order of things?

2022-10-20 22:28 UTC, maxagin commented
> The problem with this approach is that people don't see now the plots dashboard itself when they open the page (they would need to scroll). Should we change the order of things?

Maybe we can rename the section titles e.g. 

- Experiments View ~~Experiments Table~~
- Plots View ~~Plots Dashboard~~

<img width="1207" alt="Screen Shot 2022-10-20 at 6 21 50 PM" src="https://user-images.githubusercontent.com/98249521/197070905-765fc008-7acb-497e-8491-ee226812e801.png">

WDYT?

Otherwise, we need to change the textual content I think.

---

> that people don't see now the plots dashboard

Before it also was not at the top!

<img width="1217" alt="Screen Shot 2022-10-20 at 6 27 10 PM" src="https://user-images.githubusercontent.com/98249521/197070869-8f7e1b23-803b-4216-bce0-0273d6d17e04.png">

2022-10-21 00:01 UTC, shcheklein commented
@maxagin re renaming - let's do one thing at at a time please ;)

Was it at least somewhat visible? My point is that even if it was bad we are making it worse. Should we reorder things a bit?

2022-10-21 03:42 UTC, shcheklein commented
@maxagin feel too much and more images to maintain.

2022-10-26 00:08 UTC, shcheklein commented
@maxagin so, how about changing the order and finally merging this and the second PR (we can release everything today / tomorrow then)?

2022-10-26 16:36 UTC, maxagin commented
> more images to maintain.

1. Three more images won't make any difference if all the images will have to be changed.
2. Personally I think this is a very clever idea - to show right away the main extension views, thus we can educate the user about what he can expect and hopefully reduce the number of leaving users.

> changing the order

I am not sure this is good, as the content of this section is clearly organized to explain what you need to do step by step: 
1. What to do to show EXPs in Plots view
2. Types of plots
3. Explaining the types

@shcheklein, what is your take on this?

2022-11-02 05:12 UTC, shcheklein commented
@maxagin any updates on this? :)

2022-11-02 14:57 UTC, maxagin commented
Completely went out of my radar! I will deal with it ASAP @shcheklein

2022-11-03 17:55 UTC, shcheklein commented
@maxagin could you update / or upload the video please?

2022-11-03 19:58 UTC, maxagin commented
@shcheklein the description video is updated.

2022-11-03 22:33 UTC, shcheklein approved these changes

2022-11-04 01:35 UTC, merged