Maximagin patch 1 2
iterative/vscode-dvc pull request #2588
Opened 2022-10-13 20:42 UTC by maxagin

2022-10-13 22:29 UTC, sroy3 requested changes

2022-10-13 22:29 UTC, sroy3 commented on extension/resources/walkthrough/plots.md
> +```yaml
These are all python snippets and not yaml

2022-10-13 22:29 UTC, sroy3 commented on extension/resources/walkthrough/setup-project.md
> +```yaml
This snippet and the next one are also python snippets.

2022-10-14 00:04 UTC, shcheklein requested changes
This time we have two PR in one (unrelated changes). Also, go ahead and remove the images and commented code.

2022-10-14 17:31 UTC, sroy3 commented on extension/resources/walkthrough/plots.md
> +---
This look like a merge conflict indicator. Is that wanted?

2022-10-14 18:14 UTC, maxagin commented
> This time we have two PR in one (unrelated changes). 

How can I fix this please

2022-10-14 21:46 UTC, shcheklein reviewed
LGTM. Can you please show the video demo as we usually do in the description for the other PRs.

2022-10-17 15:29 UTC, maxagin commented on extension/resources/walkthrough/setup-project.md
> +        cash: false
You right. Fixing it now. Thank you @sroy3

2022-10-17 15:38 UTC, sroy3 commented on extension/resources/walkthrough/setup-project.md
> +        cashe: false
There is still a typo: `cashe` should be `cache`

2022-10-17 17:51 UTC, sroy3 approved these changes

2022-10-25 20:37 UTC, julieg18 commented
Is there a reason we haven't merged this yet? Looks like it has three approvals. cc @maxagin

2022-10-25 23:54 UTC, shcheklein approved these changes

2022-10-25 23:55 UTC, shcheklein commented
Thanks @maxagin , good stuff, let's merge it!

2022-10-25 23:56 UTC, merged