Improve the walkthrough image style
iterative/vscode-dvc pull request #2600
Opened 2022-10-15 15:17 UTC by maxagin

2022-10-16 20:16 UTC, mattseddon requested changes
You have deleted some files that are being used in the walkthrough. E.g `extension/resources/walkthrough/images/plots-dump-image.png`:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/196056167-66776e39-8d5a-490f-af3c-924ac9ecd6a5.png">

Please check that all of the walkthrough is rendered as expected.

2022-10-17 15:48 UTC, maxagin commented
Sorry @mattseddon , I thought the images are replaced with the code snippets. Will create an update now.

2022-10-17 22:30 UTC, mattseddon commented
@maxagin all of the experiments table screenshots are out of date already.

2022-10-17 23:14 UTC, maxagin commented
> @maxagin all of the experiments table screenshots are out of date already.

@mattseddon do you suggest replacing all the old screenshots?

2022-10-17 23:47 UTC, mattseddon commented
> > @maxagin all of the experiments table screenshots are out of date already.
> 
> @mattseddon do you suggest replacing all the old screenshots?

If you are going to take the time to change them then they should be correct.

2022-10-18 01:35 UTC, mattseddon commented on extension/resources/walkthrough/plots.md
> +  <img src="images/plots-click-the-circle-beside-experiment-name.png"
This one is still missing: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/196314754-1cc51299-e252-44d8-928c-272db4cbb86e.png">

2022-10-18 01:37 UTC, mattseddon submitted a review, later dismissed
Please check that all images work and record a demo for the description

2022-10-19 05:30 UTC, mattseddon commented
> When the info looks more professional we have better chances to have the user's focus.
> 
>  Screen.Recording.2022-10-18.at.11.33.50.PM.mov 
> [iterative/design#42](https://github.com/iterative/design/issues/42)

@maxagin the demo should be from inside the product.

2022-11-12 02:58 UTC, shcheklein commented
@mattseddon @maxagin what is left here folks?

2022-11-20 03:06 UTC, mattseddon commented
@shcheklein resolving the conflict isn't worth the effort as this branch pre-dates the demo project being moved into a submodule. I'll lift the images from this branch into a new one and open a new PR.

2022-11-20 21:53 UTC, closed without merging