Move context menu stuff lower level component (2/2)
iterative/vscode-dvc pull request #2643
Opened 2022-10-20 16:53 UTC by wolmir

WIP follow-up of #2593

2022-10-21 13:28 UTC, sroy3 commented
The actions do not work it triggered from the placeholder:

https://user-images.githubusercontent.com/3683420/197207133-83a54bc5-eb71-432a-b642-84c0cb59a0a8.mov

2022-10-21 13:57 UTC, wolmir commented
> The actions do not work it triggered from the placeholder

Thanks! I'll try to add a test for the placeholder case

2022-10-25 16:01 UTC, wolmir commented on extension/src/experiments/columns/model.test.ts
> +    it('should unselect the toggled children of an unselected column', async () => {
This is the failing test for https://github.com/iterative/vscode-dvc/pull/2593#discussion_r1001869678

It took some time to find the issue. I will start fixing them today

2022-10-27 14:20 UTC, sroy3 commented
> The actions do not work it triggered from the placeholder:
> 
>  Screen.Recording.2022-10-21.at.9.27.23.AM.mov

I'm getting the same thing. Is that normal?

2022-10-30 21:21 UTC, wolmir commented
> > The actions do not work it triggered from the placeholder:
> > Screen.Recording.2022-10-21.at.9.27.23.AM.mov
> 
> I'm getting the same thing. Is that normal?

No, not normal, it's sending the placeholder's synthetic id instead of the actual column id as the message payload. I'll fix it, thanks!

2022-11-07 17:38 UTC, wolmir commented
@sroy3 @julieg18 Can you take another look here please?

2022-11-07 22:57 UTC, julieg18 reviewed
Looks like `yarn lint` is failing. Can you correct the problem?

2022-11-08 14:03 UTC, sroy3 commented
> > > The actions do not work it triggered from the placeholder:
> > > Screen.Recording.2022-10-21.at.9.27.23.AM.mov
> > 
> > 
> > I'm getting the same thing. Is that normal?
> 
> No, not normal, it's sending the placeholder's synthetic id instead of the actual column id as the message payload. I'll fix it, thanks!

It's still the same.

2022-11-08 14:06 UTC, sroy3 requested changes

2022-11-11 15:10 UTC, sroy3 commented
Fixed sorting on placeholders


https://user-images.githubusercontent.com/3683420/201367956-2bfca67b-b095-4326-a69e-3226e3478d16.mov

What's missing is hiding only columns underneath a parent, but I think we should do this as a follow-up

https://user-images.githubusercontent.com/3683420/201368426-c3527166-d799-4441-ac1e-8343bed82341.mov

2022-11-11 15:50 UTC, sroy3 approved these changes

2022-11-11 18:55 UTC, merged